// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b33cc4dc-c07d-4e54-9789-5edac6a06d71",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ShrJYfqYA",
    "aws_user_pools_web_client_id": "65r2ploccj803cq520iipbmme5",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "devDB",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
